import MainLayout from '@/components/layout'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from "next/image";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ft_transcendence',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          {children}
      </body>
    </html>
  );
}
