version: "3.9"

services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=gab182
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=transDB
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./frontend/.env.local
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #     - postgres
  #   networks:
  #     - backend

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - "3001:3001"
  #     - "5555:5555"
  #     - "8005:8005"
  #     - "8001:8001"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - backend

volumes:
  postgres:

networks:
  backend:
