version: '3.9'


services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=gab182
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=transDB
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - backend


  # nest:
  #   build:
  #     context: ./backend
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - backend
  #   volumes:
  #     - backend:/app
  #   env_file:
  #     - ./backend/.env
  #   restart: on-failure
  #   depends_on:
  #     - postgres


  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - backend
  #   env_file:
  #     - ./frontend/.env.local


networks:
  backend:


volumes:
  postgres:
  # backend: