version: "3.9"

services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=gab182
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=transDB
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./frontend/.env.local
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   networks:
  #     - backend

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - "3001:3001"
  #     - "5555:5555" # Add this line to expose Prisma Studio port
  #   depends_on:
  #     - postgres
  #   networks:
  #     - backend

volumes:
  postgres:

networks:
  backend:
