version: '3.9'

services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=gab182
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=transDB
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
  # db-data: