version: '3.9'
services:
  db:
    build:
      context: .
      dockerfile: postgres_db/Dockerfile
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
