CREATE TABLE "USERS" (
  "ID" SERIAL PRIMARY KEY,
  "LOGIN_ID" VARCHAR(50) UNIQUE NOT NULL,
  "EMAIL" VARCHAR(50) UNIQUE NOT NULL,
  "NAME" VARCHAR(100),
  "PROFILE_PIC" VARCHAR(255),
  "CREATED_AT" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "UPDATED_AT" timestamptz DEFAULT (CURRENT_TIMESTAMP)
);