import Background from '@/components/Background/Background';
import MainLayout from '@/components/layout';
// import './globals.css'
import type { Metadata } from 'next';
import { ToastContainer } from 'react-toastify';
import Providers from '../(auth)/providers';

export const metadata: Metadata = {
  title: 'ft_transcendence',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Background />
          <MainLayout>
            {children}
            <ToastContainer position="top-right" />
          </MainLayout>
        </Providers>
      </body>
    </html>
  );
}
