-- CreateTable
CREATE TABLE "USERS" (
    "ID" SERIAL NOT NULL,
    "LOGIN_ID" VARCHAR(50) NOT NULL,
    "EMAIL" VARCHAR(50) NOT NULL,
    "NAME" VARCHAR(100),
    "PROFILE_PIC" VARCHAR(255),
    "CREATED_AT" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "USERS_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "USERS_LOGIN_ID_key" ON "USERS"("LOGIN_ID");

-- CreateIndex
CREATE UNIQUE INDEX "USERS_EMAIL_key" ON "USERS"("EMAIL");
